var tagID=document.getElementById("highlight");
console.log(tagID);
var tagClass=document.getElementsByClassName("Bolded");
console.log(tagClass);
var tagName=document.getElementsByTagName("li");
console.log(tagName);
var h1tag=document.querySelector("h1");
console.log(h1tag); 
var Alltag=document.querySelectorAll("li");
console.log(Alltag);
